# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created: Sat Jan 28 14:42:19 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_wnd_main(object):
    def setupUi(self, wnd_main):
        wnd_main.setObjectName(_fromUtf8("wnd_main"))
        wnd_main.resize(700, 500)
        wnd_main.setMinimumSize(QtCore.QSize(700, 500))
        wnd_main.setWindowTitle(QtGui.QApplication.translate("wnd_main", "E-learning", None, QtGui.QApplication.UnicodeUTF8))
        wnd_main.setToolTip(_fromUtf8(""))
        wnd_main.setWhatsThis(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(wnd_main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.vlt_all = QtGui.QVBoxLayout()
        self.vlt_all.setObjectName(_fromUtf8("vlt_all"))
        self.hlt_canvas_session_formula = QtGui.QHBoxLayout()
        self.hlt_canvas_session_formula.setObjectName(_fromUtf8("hlt_canvas_session_formula"))
        self.btn_canvas_session = QtGui.QPushButton(self.centralwidget)
        self.btn_canvas_session.setText(QtGui.QApplication.translate("wnd_main", "Canvas session", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_canvas_session.setCheckable(True)
        self.btn_canvas_session.setChecked(True)
        self.btn_canvas_session.setAutoDefault(False)
        self.btn_canvas_session.setDefault(False)
        self.btn_canvas_session.setFlat(False)
        self.btn_canvas_session.setObjectName(_fromUtf8("btn_canvas_session"))
        self.hlt_canvas_session_formula.addWidget(self.btn_canvas_session)
        self.vlt_formula = QtGui.QVBoxLayout()
        self.vlt_formula.setObjectName(_fromUtf8("vlt_formula"))
        self.lab_insert_formula = QtGui.QLabel(self.centralwidget)
        self.lab_insert_formula.setText(QtGui.QApplication.translate("wnd_main", "Insert formula:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_insert_formula.setObjectName(_fromUtf8("lab_insert_formula"))
        self.vlt_formula.addWidget(self.lab_insert_formula)
        self.eln_insert_formula = QtGui.QLineEdit(self.centralwidget)
        self.eln_insert_formula.setObjectName(_fromUtf8("eln_insert_formula"))
        self.vlt_formula.addWidget(self.eln_insert_formula)
        self.hlt_canvas_session_formula.addLayout(self.vlt_formula)
        self.btn_insert_formula = QtGui.QPushButton(self.centralwidget)
        self.btn_insert_formula.setText(QtGui.QApplication.translate("wnd_main", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_insert_formula.setObjectName(_fromUtf8("btn_insert_formula"))
        self.hlt_canvas_session_formula.addWidget(self.btn_insert_formula)
        self.vlt_all.addLayout(self.hlt_canvas_session_formula)
        self.hlt_canvas_menu_buttons = QtGui.QHBoxLayout()
        self.hlt_canvas_menu_buttons.setObjectName(_fromUtf8("hlt_canvas_menu_buttons"))
        self.vlt_menu_buttons = QtGui.QVBoxLayout()
        self.vlt_menu_buttons.setObjectName(_fromUtf8("vlt_menu_buttons"))
        self.btn_color = QtGui.QPushButton(self.centralwidget)
        self.btn_color.setText(QtGui.QApplication.translate("wnd_main", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_color.setCheckable(False)
        self.btn_color.setObjectName(_fromUtf8("btn_color"))
        self.vlt_menu_buttons.addWidget(self.btn_color)
        self.btn_size = QtGui.QPushButton(self.centralwidget)
        self.btn_size.setText(QtGui.QApplication.translate("wnd_main", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_size.setObjectName(_fromUtf8("btn_size"))
        self.vlt_menu_buttons.addWidget(self.btn_size)
        self.btn_clear = QtGui.QPushButton(self.centralwidget)
        self.btn_clear.setText(QtGui.QApplication.translate("wnd_main", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.vlt_menu_buttons.addWidget(self.btn_clear)
        self.btn_add = QtGui.QPushButton(self.centralwidget)
        self.btn_add.setText(QtGui.QApplication.translate("wnd_main", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.vlt_menu_buttons.addWidget(self.btn_add)
        self.btn_undo = QtGui.QPushButton(self.centralwidget)
        self.btn_undo.setText(QtGui.QApplication.translate("wnd_main", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_undo.setObjectName(_fromUtf8("btn_undo"))
        self.vlt_menu_buttons.addWidget(self.btn_undo)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlt_menu_buttons.addItem(spacerItem)
        self.hlt_canvas_menu_buttons.addLayout(self.vlt_menu_buttons)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.hlt_canvas_menu_buttons.addWidget(self.graphicsView)
        self.vlt_all.addLayout(self.hlt_canvas_menu_buttons)
        self.hlt_audio_save = QtGui.QHBoxLayout()
        self.hlt_audio_save.setObjectName(_fromUtf8("hlt_audio_save"))
        self.btn_audio_session = QtGui.QPushButton(self.centralwidget)
        self.btn_audio_session.setText(QtGui.QApplication.translate("wnd_main", "Audio session", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_audio_session.setCheckable(True)
        self.btn_audio_session.setObjectName(_fromUtf8("btn_audio_session"))
        self.hlt_audio_save.addWidget(self.btn_audio_session)
        self.btn_mute = QtGui.QPushButton(self.centralwidget)
        self.btn_mute.setText(QtGui.QApplication.translate("wnd_main", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mute.setCheckable(True)
        self.btn_mute.setObjectName(_fromUtf8("btn_mute"))
        self.hlt_audio_save.addWidget(self.btn_mute)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlt_audio_save.addItem(spacerItem1)
        self.vlt_all.addLayout(self.hlt_audio_save)
        self.horizontalLayout_4.addLayout(self.vlt_all)
        wnd_main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(wnd_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.men_options = QtGui.QMenu(self.menubar)
        self.men_options.setTitle(QtGui.QApplication.translate("wnd_main", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.men_options.setObjectName(_fromUtf8("men_options"))
        self.men_help = QtGui.QMenu(self.menubar)
        self.men_help.setTitle(QtGui.QApplication.translate("wnd_main", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.men_help.setObjectName(_fromUtf8("men_help"))
        self.men_file = QtGui.QMenu(self.menubar)
        self.men_file.setTitle(QtGui.QApplication.translate("wnd_main", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.men_file.setObjectName(_fromUtf8("men_file"))
        self.men_save_as = QtGui.QMenu(self.men_file)
        self.men_save_as.setTitle(QtGui.QApplication.translate("wnd_main", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.men_save_as.setObjectName(_fromUtf8("men_save_as"))
        wnd_main.setMenuBar(self.menubar)
        self.stb_main = QtGui.QStatusBar(wnd_main)
        self.stb_main.setObjectName(_fromUtf8("stb_main"))
        wnd_main.setStatusBar(self.stb_main)
        self.act_color = QtGui.QAction(wnd_main)
        self.act_color.setText(QtGui.QApplication.translate("wnd_main", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.act_color.setShortcut(QtGui.QApplication.translate("wnd_main", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.act_color.setObjectName(_fromUtf8("act_color"))
        self.act_size = QtGui.QAction(wnd_main)
        self.act_size.setText(QtGui.QApplication.translate("wnd_main", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.act_size.setShortcut(QtGui.QApplication.translate("wnd_main", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.act_size.setObjectName(_fromUtf8("act_size"))
        self.act_add = QtGui.QAction(wnd_main)
        self.act_add.setText(QtGui.QApplication.translate("wnd_main", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.act_add.setShortcut(QtGui.QApplication.translate("wnd_main", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.act_add.setObjectName(_fromUtf8("act_add"))
        self.act_undo = QtGui.QAction(wnd_main)
        self.act_undo.setText(QtGui.QApplication.translate("wnd_main", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.act_undo.setShortcut(QtGui.QApplication.translate("wnd_main", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.act_undo.setObjectName(_fromUtf8("act_undo"))
        self.act_settings = QtGui.QAction(wnd_main)
        self.act_settings.setText(QtGui.QApplication.translate("wnd_main", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.act_settings.setShortcut(QtGui.QApplication.translate("wnd_main", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.act_settings.setObjectName(_fromUtf8("act_settings"))
        self.act_clear = QtGui.QAction(wnd_main)
        self.act_clear.setText(QtGui.QApplication.translate("wnd_main", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.act_clear.setShortcut(QtGui.QApplication.translate("wnd_main", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.act_clear.setObjectName(_fromUtf8("act_clear"))
        self.act_jpg = QtGui.QAction(wnd_main)
        self.act_jpg.setText(QtGui.QApplication.translate("wnd_main", ".jpg", None, QtGui.QApplication.UnicodeUTF8))
        self.act_jpg.setObjectName(_fromUtf8("act_jpg"))
        self.act_bmp = QtGui.QAction(wnd_main)
        self.act_bmp.setText(QtGui.QApplication.translate("wnd_main", ".bmp", None, QtGui.QApplication.UnicodeUTF8))
        self.act_bmp.setObjectName(_fromUtf8("act_bmp"))
        self.men_options.addAction(self.act_color)
        self.men_options.addAction(self.act_size)
        self.men_options.addAction(self.act_clear)
        self.men_options.addAction(self.act_add)
        self.men_options.addAction(self.act_undo)
        self.men_options.addSeparator()
        self.men_options.addAction(self.act_settings)
        self.men_save_as.addAction(self.act_jpg)
        self.men_save_as.addAction(self.act_bmp)
        self.men_file.addAction(self.men_save_as.menuAction())
        self.menubar.addAction(self.men_file.menuAction())
        self.menubar.addAction(self.men_options.menuAction())
        self.menubar.addAction(self.men_help.menuAction())

        self.retranslateUi(wnd_main)
        QtCore.QMetaObject.connectSlotsByName(wnd_main)
        wnd_main.setTabOrder(self.btn_canvas_session, self.eln_insert_formula)
        wnd_main.setTabOrder(self.eln_insert_formula, self.btn_insert_formula)
        wnd_main.setTabOrder(self.btn_insert_formula, self.btn_color)
        wnd_main.setTabOrder(self.btn_color, self.btn_size)
        wnd_main.setTabOrder(self.btn_size, self.btn_clear)
        wnd_main.setTabOrder(self.btn_clear, self.btn_add)
        wnd_main.setTabOrder(self.btn_add, self.btn_undo)
        wnd_main.setTabOrder(self.btn_undo, self.btn_audio_session)
        wnd_main.setTabOrder(self.btn_audio_session, self.btn_mute)
        wnd_main.setTabOrder(self.btn_mute, self.graphicsView)

    def retranslateUi(self, wnd_main):
        pass

